### ISSUE TITLE
avoid global variables

### ISSUE THREAD

**Issue by dneise** [fact-project/drsTemperatureCalibration#2]
global variables can make code harder to understand. try to avoid them

**Comment by dneise** [comment]
Ah now I see ... you are using some global constants and just *read* them, never write. 
I think that's fine.

A typical way of marking a global constant is basically to use all caps, like:

```
SOME_CONST = 7
NAME = "Dominik"

def my_func():
    print(SOME_CONST * NAME)
```

**Comment by dneise** [comment]
no need to use `global` inside a function **reading** these global constants ... you just need to use the `global` keyword if you want to write into such a global constant. (which is generally a bad idea, so in case you are doing it, you at least have to show it to everybody by using the `global` keyword) 

look at this example:
```python
CONST = 7

def func1():
    CONST = 8  # this is not changing the global "CONST" 
    # instead it is creating a *local* variable called also CONST
    # which is just *shadowing* the global variable

def func2():
    global CONST
    CONST = 8  # this does really change the global CONST

print(CONST)
func1()
print(CONST)
func2()
print(CONST)

```

**Comment by FlorianS01** [comment]
ahh ok, good to know
